Debugging GitHub CI

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,124 +29,124 @@ env:
   WORKSPACEPATH: .swiftpm/xcode/package.xcworkspace
 
 jobs:
-  macOS:
-    name: Tests (macOS)
-    runs-on: macos-latest
-    timeout-minutes: 30
-    steps:
-    - uses: actions/checkout@main
-    - uses: maxim-lobanov/setup-xcode@v1
-      with:
-        xcode-version: latest-stable
-    - name: Build
-      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    - name: Unit Tests
-      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-  
-  macOS-swift6-2:
-    name: Tests (macOS - Swift 6.2)
-    runs-on: macos-latest
-    timeout-minutes: 30
-    steps:
-    - uses: actions/checkout@main
-    - uses: maxim-lobanov/setup-xcode@v1
-      with:
-        xcode-version: latest-stable
-    - name: Set Package to Swift 6.2
-      run: swift package tools-version --set "6.2"
-    - name: Build
-      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    - name: Unit Tests
-      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      
-  macCatalyst:
-    name: Tests (macCatalyst)
-    runs-on: macos-latest
-    timeout-minutes: 30
-    steps:
-    - uses: actions/checkout@main
-    - uses: maxim-lobanov/setup-xcode@v1
-      with:
-        xcode-version: latest-stable
-    - name: Build
-      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-    - name: Unit Tests
-      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-
-  device-simulators:
-    name: Tests
-    runs-on: macos-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        target: [iOS, tvOS, watchOS, visionOS]
-    timeout-minutes: 30
-    steps:
-    - uses: actions/checkout@main
-    - uses: maxim-lobanov/setup-xcode@v1
-      with:
-        xcode-version: latest-stable
-    - name: Prepare Device Simulator
-      id: sim-setup
-      uses: orchetect/setup-xcode-simulator@v1
-      with:
-        refresh: true
-        download: true
-        scheme: ${{ env.SCHEME }}
-        target: ${{ matrix.target }}
-    - name: Build
-      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=$PLATFORMSHORT" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      env:
-        PLATFORMSHORT: ${{ steps.sim-setup.outputs.platform-short }}
-        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
-    - name: Unit Tests
-      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=$PLATFORM,id=$ID" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
-      env:
-        ID: ${{ steps.sim-setup.outputs.id }}
-        PLATFORM: ${{ steps.sim-setup.outputs.platform }}
-        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
-  
-  linux:
-    name: Tests (Linux)
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    steps:
-    - uses: actions/checkout@main
-    - name: Build
-      run: swift build
-    - name: Unit Tests
-      run: swift test
-
-  android:
-    name: Build (Android)
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    env:
-      TARGET_TRIPLE: aarch64-unknown-linux-android28
-    steps:
-    - uses: actions/checkout@main
-    - uses: orchetect/setup-swift-android-sdk@v1
-      with:
-        target-triple: ${{ env.TARGET_TRIPLE }}
-    - name: Build
-      run: swift build --swift-sdk "$TARGET_TRIPLE" --static-swift-stdlib
-
-  wasm-on-linux:
-    name: Build (WASM on Linux)
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
-    env:
-      TARGET_TRIPLE: wasm32-unknown-wasip1
-    steps:
-    - uses: actions/checkout@v1
-    - uses: orchetect/setup-swift-wasm-sdk@main
-      id: sdk-setup
-      with:
-        target-triple: ${{ env.TARGET_TRIPLE }}
-    - name: Build
-      run: swift build --swift-sdk "$SDK_ID" --triple "$TARGET_TRIPLE"
-      env:
-        SDK_ID: ${{ steps.sdk-setup.outputs.id }}
+#  macOS:
+#    name: Tests (macOS)
+#    runs-on: macos-latest
+#    timeout-minutes: 30
+#    steps:
+#    - uses: actions/checkout@main
+#    - uses: maxim-lobanov/setup-xcode@v1
+#      with:
+#        xcode-version: latest-stable
+#    - name: Build
+#      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+#    - name: Unit Tests
+#      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+#
+#  macOS-swift6-2:
+#    name: Tests (macOS - Swift 6.2)
+#    runs-on: macos-latest
+#    timeout-minutes: 30
+#    steps:
+#    - uses: actions/checkout@main
+#    - uses: maxim-lobanov/setup-xcode@v1
+#      with:
+#        xcode-version: latest-stable
+#    - name: Set Package to Swift 6.2
+#      run: swift package tools-version --set "6.2"
+#    - name: Build
+#      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+#    - name: Unit Tests
+#      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=macOS" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+#
+#  macCatalyst:
+#    name: Tests (macCatalyst)
+#    runs-on: macos-latest
+#    timeout-minutes: 30
+#    steps:
+#    - uses: actions/checkout@main
+#    - uses: maxim-lobanov/setup-xcode@v1
+#      with:
+#        xcode-version: latest-stable
+#    - name: Build
+#      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+#    - name: Unit Tests
+#      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=macOS,variant=Mac Catalyst" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+#
+#  device-simulators:
+#    name: Tests
+#    runs-on: macos-latest
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        target: [iOS, tvOS, watchOS, visionOS]
+#    timeout-minutes: 30
+#    steps:
+#    - uses: actions/checkout@main
+#    - uses: maxim-lobanov/setup-xcode@v1
+#      with:
+#        xcode-version: latest-stable
+#    - name: Prepare Device Simulator
+#      id: sim-setup
+#      uses: orchetect/setup-xcode-simulator@v1
+#      with:
+#        refresh: true
+#        download: true
+#        scheme: ${{ env.SCHEME }}
+#        target: ${{ matrix.target }}
+#    - name: Build
+#      run: xcodebuild build -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "generic/platform=$PLATFORMSHORT" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+#      env:
+#        PLATFORMSHORT: ${{ steps.sim-setup.outputs.platform-short }}
+#        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
+#    - name: Unit Tests
+#      run: xcodebuild test -skipMacroValidation -workspace "$WORKSPACEPATH" -scheme "$SCHEME" -destination "platform=$PLATFORM,id=$ID" | xcbeautify --renderer github-actions && exit ${PIPESTATUS[0]}
+#      env:
+#        ID: ${{ steps.sim-setup.outputs.id }}
+#        PLATFORM: ${{ steps.sim-setup.outputs.platform }}
+#        WORKSPACEPATH: ${{ steps.sim-setup.outputs.workspace-path }}
+#
+#  linux:
+#    name: Tests (Linux)
+#    runs-on: ubuntu-latest
+#    timeout-minutes: 30
+#    steps:
+#    - uses: actions/checkout@main
+#    - name: Build
+#      run: swift build
+#    - name: Unit Tests
+#      run: swift test
+#
+#  android:
+#    name: Build (Android)
+#    runs-on: ubuntu-latest
+#    timeout-minutes: 30
+#    env:
+#      TARGET_TRIPLE: aarch64-unknown-linux-android28
+#    steps:
+#    - uses: actions/checkout@main
+#    - uses: orchetect/setup-swift-android-sdk@v1
+#      with:
+#        target-triple: ${{ env.TARGET_TRIPLE }}
+#    - name: Build
+#      run: swift build --swift-sdk "$TARGET_TRIPLE" --static-swift-stdlib
+#
+#  wasm-on-linux:
+#    name: Build (WASM on Linux)
+#    runs-on: ubuntu-latest
+#    timeout-minutes: 30
+#    env:
+#      TARGET_TRIPLE: wasm32-unknown-wasip1
+#    steps:
+#    - uses: actions/checkout@v1
+#    - uses: orchetect/setup-swift-wasm-sdk@main
+#      id: sdk-setup
+#      with:
+#        target-triple: ${{ env.TARGET_TRIPLE }}
+#    - name: Build
+#      run: swift build --swift-sdk "$SDK_ID" --triple "$TARGET_TRIPLE"
+#      env:
+#        SDK_ID: ${{ steps.sdk-setup.outputs.id }}
 
   wasm-on-macos:
     name: Build (WASM on macOS)
@@ -161,7 +161,6 @@ jobs:
       with:
         target-triple: ${{ env.TARGET_TRIPLE }}
     - name: Build
-      run: swift build --swift-sdk "$SDK_ID"
+      run: swift build --swift-sdk "$SDK_ID" --triple "$TARGET_TRIPLE" --verbose
       env:
         SDK_ID: ${{ steps.sdk-setup.outputs.id }}
-
